export const companies = [
  {
    id: 1,
    companyName: 'Alpha Corp',
    companyNickName: 'Alpha',
    address: '123 Alpha Street, Cityville',
    vat: 12,
    ewt: 2,
  },
  {
    id: 2,
    companyName: 'Beta Industries',
    companyNickName: 'Beta',
    address: '456 Beta Ave, Townland',
    vat: 10,
    ewt: 1,
  },
  {
    id: 3,
    companyName: 'Gamma Solutions',
    companyNickName: 'Gamma',
    address: '789 Gamma Blvd, Metrocity',
    vat: 5,
    ewt: 2,
  },
  {
    id: 4,
    companyName: 'Delta Enterprises',
    companyNickName: 'Delta',
    address: '321 Delta Rd, Suburbia',
    vat: 8,
    ewt: 1,
  },
  {
    id: 5,
    companyName: 'Epsilon LLC',
    companyNickName: 'Epsilon',
    address: '654 Epsilon Lane, Uptown',
    vat: 7,
    ewt: 2,
  },
  {
    id: 6,
    companyName: 'Zeta Technologies',
    companyNickName: 'ZetaTech',
    address: '987 Zeta Park, Midtown',
    vat: 10,
    ewt: 1,
  },
  {
    id: 7,
    companyName: 'Eta Innovations',
    companyNickName: 'Eta',
    address: '147 Eta St, Cityside',
    vat: 12,
    ewt: 2,
  },
  {
    id: 8,
    companyName: 'Theta Group',
    companyNickName: 'Theta',
    address: '258 Theta Dr, Villagetown',
    vat: 9,
    ewt: 1,
  },
  {
    id: 9,
    companyName: 'Iota Systems',
    companyNickName: 'Iota',
    address: '369 Iota Way, Countryside',
    vat: 11,
    ewt: 2,
  },
  {
    id: 10,
    companyName: 'Kappa Labs',
    companyNickName: 'Kappa',
    address: '159 Kappa Blvd, Newtown',
    vat: 6,
    ewt: 1,
  },
  {
    id: 11,
    companyName: 'Lambda Partners',
    companyNickName: 'Lambda',
    address: '753 Lambda Rd, Central City',
    vat: 10,
    ewt: 2,
  },
  {
    id: 12,
    companyName: 'Mu Corp',
    companyNickName: 'Mu',
    address: '852 Mu Lane, Eastside',
    vat: 9,
    ewt: 1,
  },
  {
    id: 13,
    companyName: 'Nu Solutions',
    companyNickName: 'Nu',
    address: '951 Nu Ave, Westfield',
    vat: 11,
    ewt: 2,
  },
  {
    id: 14,
    companyName: 'Xi Enterprises',
    companyNickName: 'Xi',
    address: '357 Xi Dr, Northpoint',
    vat: 7,
    ewt: 1,
  },
  {
    id: 15,
    companyName: 'Omicron Inc',
    companyNickName: 'Omicron',
    address: '258 Omicron St, Southgate',
    vat: 8,
    ewt: 2,
  },
  {
    id: 16,
    companyName: 'Pi Holdings',
    companyNickName: 'Pi',
    address: '369 Pi Blvd, Riverside',
    vat: 10,
    ewt: 1,
  },
  {
    id: 17,
    companyName: 'Rho Global',
    companyNickName: 'Rho',
    address: '147 Rho Park, Hilltop',
    vat: 12,
    ewt: 2,
  },
  {
    id: 18,
    companyName: 'Sigma Ventures',
    companyNickName: 'Sigma',
    address: '789 Sigma Ave, Bayview',
    vat: 9,
    ewt: 1,
  },
  {
    id: 19,
    companyName: 'Tau Networks',
    companyNickName: 'Tau',
    address: '456 Tau Dr, Lakeside',
    vat: 6,
    ewt: 2,
  },
  {
    id: 20,
    companyName: 'Upsilon Dynamics',
    companyNickName: 'Upsilon',
    address: '123 Upsilon St, Highland',
    vat: 8,
    ewt: 1,
  },
  {
    id: 21,
    companyName: 'Phi Works',
    companyNickName: 'Phi',
    address: '741 Phi Blvd, Midtown',
    vat: 7,
    ewt: 2,
  },
  {
    id: 22,
    companyName: 'Chi Creations',
    companyNickName: 'Chi',
    address: '852 Chi Rd, Villagewest',
    vat: 11,
    ewt: 1,
  },
  {
    id: 23,
    companyName: 'Psi Digital',
    companyNickName: 'Psi',
    address: '963 Psi Ln, Oldtown',
    vat: 5,
    ewt: 2,
  },
  {
    id: 24,
    companyName: 'Omega Logistics',
    companyNickName: 'Omega',
    address: '159 Omega Ave, Greentown',
    vat: 9,
    ewt: 1,
  },
  {
    id: 25,
    companyName: 'Nova Technologies',
    companyNickName: 'Nova',
    address: '753 Nova St, Springfield',
    vat: 10,
    ewt: 2,
  },
  {
    id: 26,
    companyName: 'Quasar Holdings',
    companyNickName: 'Quasar',
    address: '852 Quasar Blvd, Midtown',
    vat: 12,
    ewt: 1,
  },
  {
    id: 27,
    companyName: 'Stellar Systems',
    companyNickName: 'Stellar',
    address: '951 Stellar Ave, Citygate',
    vat: 8,
    ewt: 2,
  },
  {
    id: 28,
    companyName: 'Pioneer Group',
    companyNickName: 'Pioneer',
    address: '357 Pioneer Dr, Creekside',
    vat: 11,
    ewt: 1,
  },
  {
    id: 29,
    companyName: 'Vector Corp',
    companyNickName: 'Vector',
    address: '258 Vector Rd, Bayfront',
    vat: 10,
    ewt: 2,
  },
  {
    id: 30,
    companyName: 'Orbit Labs',
    companyNickName: 'Orbit',
    address: '369 Orbit Blvd, Highrise',
    vat: 7,
    ewt: 1,
  },
  {
    id: 31,
    companyName: 'Fusion LLC',
    companyNickName: 'Fusion',
    address: '147 Fusion Ave, Westpark',
    vat: 6,
    ewt: 2,
  },
  {
    id: 32,
    companyName: 'Infinity Inc',
    companyNickName: 'Infinity',
    address: '123 Infinity Ln, Urbania',
    vat: 9,
    ewt: 1,
  },
  {
    id: 33,
    companyName: 'Nexus Solutions',
    companyNickName: 'Nexus',
    address: '456 Nexus St, Oldbay',
    vat: 12,
    ewt: 2,
  },
  {
    id: 34,
    companyName: 'Elemental Enterprises',
    companyNickName: 'Elemental',
    address: '789 Elemental Blvd, Townview',
    vat: 11,
    ewt: 1,
  },
  {
    id: 35,
    companyName: 'Celestial Systems',
    companyNickName: 'Celestial',
    address: '321 Celestial Dr, Hillcrest',
    vat: 8,
    ewt: 2,
  },
  {
    id: 36,
    companyName: 'Core Dynamics',
    companyNickName: 'Core',
    address: '654 Core Ave, Lakeshore',
    vat: 10,
    ewt: 1,
  },
  {
    id: 37,
    companyName: 'Summit Technologies',
    companyNickName: 'Summit',
    address: '987 Summit Rd, Edgewater',
    vat: 6,
    ewt: 2,
  },
  {
    id: 38,
    companyName: 'Pinnacle Corp',
    companyNickName: 'Pinnacle',
    address: '147 Pinnacle Blvd, Downtown',
    vat: 9,
    ewt: 1,
  },
  {
    id: 39,
    companyName: 'Apex Group',
    companyNickName: 'Apex',
    address: '258 Apex Ave, Rivertown',
    vat: 10,
    ewt: 2,
  },
  {
    id: 40,
    companyName: 'Zenith Holdings',
    companyNickName: 'Zenith',
    address: '369 Zenith St, Summitville',
    vat: 7,
    ewt: 1,
  },
  {
    id: 41,
    companyName: 'Aurora Enterprises',
    companyNickName: 'Aurora',
    address: '753 Aurora Blvd, Sunnytown',
    vat: 9,
    ewt: 2,
  },
  {
    id: 42,
    companyName: 'Nimbus Corp',
    companyNickName: 'Nimbus',
    address: '852 Nimbus Rd, Rainy City',
    vat: 6,
    ewt: 1,
  },
  {
    id: 43,
    companyName: 'Vortex Technologies',
    companyNickName: 'Vortex',
    address: '951 Vortex Ave, Windside',
    vat: 11,
    ewt: 2,
  },
  {
    id: 44,
    companyName: 'Horizon Systems',
    companyNickName: 'Horizon',
    address: '357 Horizon Dr, Coastview',
    vat: 10,
    ewt: 1,
  },
  {
    id: 45,
    companyName: 'Pulse Innovations',
    companyNickName: 'Pulse',
    address: '258 Pulse Blvd, Heartland',
    vat: 8,
    ewt: 2,
  },
  {
    id: 46,
    companyName: 'Beacon Solutions',
    companyNickName: 'Beacon',
    address: '159 Beacon St, Lightcity',
    vat: 9,
    ewt: 1,
  },
  {
    id: 47,
    companyName: 'Crux Technologies',
    companyNickName: 'Crux',
    address: '654 Crux Lane, Polarville',
    vat: 12,
    ewt: 2,
  },
  {
    id: 48,
    companyName: 'Vertex Labs',
    companyNickName: 'Vertex',
    address: '123 Vertex Rd, Mountview',
    vat: 10,
    ewt: 1,
  },
  {
    id: 49,
    companyName: 'Stratus Corp',
    companyNickName: 'Stratus',
    address: '456 Stratus Dr, Cloudtop',
    vat: 7,
    ewt: 2,
  },
  {
    id: 50,
    companyName: 'Atlas Group',
    companyNickName: 'Atlas',
    address: '789 Atlas Ave, Globe City',
    vat: 6,
    ewt: 1,
  },
];
